cd ./DaySpaPet.Core
dotnet restore
cd ..
cd ./DaySpaPet.UseCases
dotnet restore
cd ..
cd ./DaySpaPet.Infrastructure
dotnet restore
cd ..
cd ./DaySpaPet.NativePlat.Client
dotnet restore
cd ..
cd ./DaySpaPet.Web
dotnet restore
cd ..
cd ./DaySpaPet.Wasm
dotnet restore
cd ..
